### ISSUE TITLE
备份到AList失败:Cannot read properties of undefined (reading 'writeText') v3.1.6

### ISSUE THREAD

**Issue by ppzha** [loonghfut/siyuan-alist#1]
我在全量备份的时候提示了这个错误，但是我发现alist上正常收到了备份文件

备份到AList失败:Cannot read properties of undefined (reading 'writeText') v3.1.6

我检查了一下是在这里
```
 l.showMessage("备份到alist成功", 6e3, "info", "备份到AList");
                    var t = `[${a}](${exports.alistUrl}${e})`;
                    navigator.clipboard.writeText(t).then(function() {
                        r("Markdown链接已复制到剪贴板", "uploadToAList")
                    }).catch(function(m) {
                        console.error("无法复制链接: ", m),
                        l.showMessage("无法复制链接", -1, "error")
                    `}),`
```
其中浏览器并不支持 navigator.clipboard

**Comment by loonghfut** [comment]
你好，感谢反馈，我一直用的edge没有出现过这个问题（只有在页面没有焦点时，会出现无法将链接写入剪切板[并不影响使用][本来这个功能是方便我上传文件后将文件的链接通过Ctrl V 插到任意位置]），确实有些浏览器不支持navigator.clipboard，后面版本我优化一下错误反馈提示。最后，我很好奇你用的是什么浏览器？

**Comment by ppzha** [comment]
![image](https://github.com/user-attachments/assets/9249494e-4d81-44c4-9010-4f62acecffba)

**Comment by ppzha** [comment]
这是我的浏览器版本，我刚接触思源笔记不久，不太清楚思源这个软件的实现方式，我猜测的是思源在windows上是基于一个chrome的浏览器内核搭建起来的，是不是该软件本身的浏览器不支持navigator.clipboard？因为我自己的浏览器本身是支持的.
![image](https://github.com/user-attachments/assets/8177c199-5dc9-483f-9466-32c624d61da0)
