### ISSUE TITLE
定时备份bug

### ISSUE THREAD

**Issue by AWicls** [loonghfut/siyuan-alist#10]
#### 问题描述:
- 定时备份时分秒会省略前面的0
- 会替换掉点击全量备份中的默认名(替换掉变量名为时间戳)
- 我也只知道咋描述了, 看图吧
#### 相关图片

![image](https://github.com/user-attachments/assets/e8e65350-ff0b-42ce-b764-e299f595f550)

![image](https://github.com/user-attachments/assets/5d62797c-5458-4060-bfd7-3523c5289288)

![image](https://github.com/user-attachments/assets/4937b59a-417b-435b-a5c0-cf2e1941fcf8)

![image](https://github.com/user-attachments/assets/6eff08fb-69de-47d3-9018-8e4cd66762bb)

**Comment by AWicls** [comment]
情况补充说明:
- 我docker端和桌面端同时在线
- 桌面端点全量备份时变量名被替换了, docker端没有, 可能时双端引起的不过?
- 或者有没有办法不同步每日备份定时的参数
- 不好解决多端看看能不能吧变量名被替换修了
- 以上问题没有测试, 因为不好复现

*如果此问题由多端引发不好解决可直接关闭此`issue`*

**Comment by loonghfut** [comment]
> 定时备份时分秒会省略前面的0

这个我晚上再测试一下，估计是个bug，晚上增加点错误处理

> 会替换掉点击全量备份中的默认名(替换掉变量名为时间戳)

这个我可以尝试修一下，晚上更新

感谢反馈，有用的不顺的地方，尽管提，我尽力解决

**Comment by loonghfut** [comment]
对了，定时在2点备份，你的思源一直没关对吧？

**Comment by AWicls** [comment]
- 思源没关
- 我的默认时间参数名被改了, 但是设置内的默认名没动, 就是点击全量备份按钮后的弹窗内的时间戳变量名被替换了
- 刚刚测试了下时分秒会省略0, 年月日就不知道
![image](https://github.com/user-attachments/assets/e1dab349-f1a0-4c88-aef6-668e9510920b)

**Comment by loonghfut** [comment]
了解，晚上修复

再次感谢帮忙测试和反馈

**Comment by AWicls** [comment]
> > 或者有没有办法不同步每日备份定时的参数
> 
> 这个是不加上时间戳的意思吗？参数，是什么参数？

- 我的意思是应该是吧这个定时备份参数额外存放, 不会通过思源同步此参数达到指定一端定时备份, 估计不好搞

**Comment by loonghfut** [comment]
达到的目的是，只让一端的思源定时备份，其他端不定时备份，对吧？

**Comment by AWicls** [comment]
> 达到的目的是，只让一端的思源定时备份，其他端不定时备份，对吧？

是的

**Comment by loonghfut** [comment]
> > 达到的目的是，只让一端的思源定时备份，其他端不定时备份，对吧？
> 
> 是的

这个功能可以实现，官方的同步可以设置忽略一些文件（用户手册里有说明），但要等之后我重构一下设置页面的时候实现了，目前没那么多时间。
但目前有一个临时解决方案，我可以只让桌面端实现自动备份，不知能否达到你的目的。若能则在明天晚上之前实现此功能

**Comment by loonghfut** [comment]
> 我可以只让桌面端实现自动备份，不知能否达到你的目的。

已实现，我简单测试了一下没有问题，如遇到bug，请反馈

**Comment by AWicls** [comment]
> 这几天出去有事儿去了, 所以现在才回复, 抱歉
- 如果发现bug或其他问题我会及时反馈
- 本评论无需回复
