### ISSUE TITLE
侧边栏拉伸有bug

### ISSUE THREAD

**Issue by Zolliner** [loonghfut/siyuan-alist#13]
侧边栏显示文件时，拉伸窗口会导致无法还原，其他侧边栏都没这个问题，只有alist的会这样
详见视频

https://github.com/user-attachments/assets/08c72847-a38e-415b-861a-92b09b28bcc8

**Comment by loonghfut** [comment]
详见 #7

**Comment by loonghfut** [comment]
这个可能是思源的问题，思源嵌入网页都有可能出现这种情况
如遇到其他嵌入网页的插件，没有遇到此问题，请告知我

目前解决办法：
拖动的时候将鼠标移动到思源笔记的下方或上方（文档栏里）

**Comment by Zolliner** [comment]
> 这个可能是思源的问题，思源嵌入网页都有可能出现这种情况 如遇到其他嵌入网页的插件，没有遇到此问题，请告知我
> 
> 目前解决办法： 拖动的时候将鼠标移动到思源笔记的下方或上方（文档栏里）

我知道有个插件可以
![图片](https://github.com/user-attachments/assets/bdb4b068-24b8-4f88-9b6d-f5658df68cac)

安装插件后，可以将一些web应用设置在右侧栏里
![图片](https://github.com/user-attachments/assets/363379de-682f-402f-87ac-00ad9617427f)

gif演示如下：
![PixPin_2024-12-05_13-45-12](https://github.com/user-attachments/assets/ab919af1-6e43-4f9d-b3a7-afdda34bda61)

**Comment by loonghfut** [comment]
感谢回复，我最近试试看能不能修复

**Comment by loonghfut** [comment]
看来不是思源的问题，是我太菜了，感谢反馈，v0.1.10版本已解决，我简单测试没有问题，若还存在bug欢迎反馈
