### ISSUE TITLE
1.快捷键冲突问题。
2.发布服务下数据安全问题。

### ISSUE THREAD

**Issue by wish5115** [loonghfut/siyuan-alist#2]
![r78](https://github.com/user-attachments/assets/8ab127e0-8ca1-4232-8f6b-8154921e0460)

**Comment by loonghfut** [comment]
这个可能是思源的问题，思源嵌入网页都有可能出现这种情况

目前解决办法：
拖动的时候将鼠标移动到思源笔记的下方或上方（文档栏里）

如还没解决，稍后我录个视频

**Comment by loonghfut** [comment]
另外，如需大页面查看，可通过Alt+左键打开一个右侧页面

**Comment by wish5115** [comment]
> 这个可能是思源的问题，思源嵌入网页都有可能出现这种情况
> 
> 目前解决办法： 拖动的时候将鼠标移动到思源笔记的下方或上方（文档栏里）
> 
> 如还没解决，稍后我录个视频

谢谢，我这边鼠标放到拖动栏的下面可以拖动了。

**Comment by loonghfut** [comment]
嗯，在使用上有什么想法欢迎反馈

**Comment by wish5115** [comment]
> 另外，如需大页面查看，可通过Alt+左键打开一个右侧页面

提到打开链接，还是有个小问题，不过影响不大，具体如下

**当使用browserTab插件的时候，表现如下**
![r78-1](https://github.com/user-attachments/assets/da0e1933-39ed-47cc-aeaf-56d9146a92b4)
同时打开新标签和右侧面板

**当使用网页视图插件的时候，表现如下**
![r78-2](https://github.com/user-attachments/assets/80ea221d-0eec-47d4-8ae6-cb9f5b1cab7d)
仅打开新标签页

**当未使用这两个插件的时候，表现如下**
![r78-3](https://github.com/user-attachments/assets/2fb9926b-a9d8-4443-999f-ffdf5f317881)
仅打开右侧面板

可能是思源本身的问题，不是插件问题吧。

**Comment by wish5115** [comment]
> 嗯，在使用上有什么想法欢迎反馈

我还真有个想法，不过和插件本身无关，不知你是否感兴趣，我打算试试。

我建议可以在alist的全局自定义内容里写个脚本，监控视频播放进度，根据播放进度在视频下方生成一个按钮，这样，拖动这个按钮的链接到思源笔记里，就会在mp4后面添加时间参数，比如xxx.mp4?time=300，然后在alist加载时再捕获这个参数，这样当从思源点击视频链接进入alist时就会自动跳转到指定的时间位置播放。


alist配置
<img width="435" alt="image" src="https://github.com/user-attachments/assets/fa25686b-6e2f-4638-9765-beb0afbe3cc5">

alist播放页面
<img width="925" alt="image" src="https://github.com/user-attachments/assets/d6e53e01-595f-457d-bbb3-7a505dfa0087">

**Comment by loonghfut** [comment]
> > 另外，如需大页面查看，可通过Alt+左键打开一个右侧页面
> 
> 提到打开链接，还是有个小问题，不过影响不大，具体如下
> 
> **当使用browserTab插件的时候，表现如下**
> ![r78-1](https://github.com/user-attachments/assets/da0e1933-39ed-47cc-aeaf-56d9146a92b4)
> 同时打开新标签和右侧面板
> 
> **当使用网页视图插件的时候，表现如下**
> ![r78-2](https://github.com/user-attachments/assets/80ea221d-0eec-47d4-8ae6-cb9f5b1cab7d)
> 仅打开新标签页
> 
> **当未使用这两个插件的时候，表现如下**
> ![r78-3](https://github.com/user-attachments/assets/2fb9926b-a9d8-4443-999f-ffdf5f317881)
> 仅打开右侧面板
> 
> 可能是思源本身的问题，不是插件问题吧。
> 
> 

这个是因为这两个插件功能有冲突，两个插件都监听了相同的事件（即点击链接事件）如果影响操作，你可以在browserTab插件里设置Ctrl＋左键来实现在思源里打开链接（如果你还是觉得不方便，我后续在我的插件里加一个设置选项[Ctrl＋左键才触发]以防止和另一个插件冲突

**Comment by loonghfut** [comment]
> > 嗯，在使用上有什么想法欢迎反馈
> 
> 我还真有个想法，不过和插件本身无关，不知你是否感兴趣，我打算试试。
> 
> 我建议可以在alist的全局自定义内容里写个脚本，监控视频播放进度，根据播放进度在视频下方生成一个按钮，这样，拖动这个按钮的链接到思源笔记里，就会在mp4后面添加时间参数，比如xxx.mp4?time=300，然后在alist加载时再捕获这个参数，这样当从思源点击视频链接进入alist时就会自动跳转到指定的时间位置播放。
> 
> 
> alist配置
> <img width="435" alt="image" src="https://github.com/user-attachments/assets/fa25686b-6e2f-4638-9765-beb0afbe3cc5">
> 
> alist播放页面
> <img width="925" alt="image" src="https://github.com/user-attachments/assets/d6e53e01-595f-457d-bbb3-7a505dfa0087">
> 

好想法，应该比较容易实现，后面有时间我尝试尝试（虽然我目前没有这方面的需求）

**Comment by wish5115** [comment]
> 这个是因为这两个插件功能有冲突，两个插件都监听了相同的事件（即点击链接事件）如果影响操作，你可以在browserTab插件里设置Ctrl＋左键来实现在思源里打开链接（如果你还是觉得不方便，我后续在我的插件里加一个设置选项[Ctrl＋左键才触发]以防止和另一个插件冲突

这个可以有。

**Comment by wish5115** [comment]
> > > 嗯，在使用上有什么想法欢迎反馈
> > 
> > 
> > 我还真有个想法，不过和插件本身无关，不知你是否感兴趣，我打算试试。
> > 我建议可以在alist的全局自定义内容里写个脚本，监控视频播放进度，根据播放进度在视频下方生成一个按钮，这样，拖动这个按钮的链接到思源笔记里，就会在mp4后面添加时间参数，比如xxx.mp4?time=300，然后在alist加载时再捕获这个参数，这样当从思源点击视频链接进入alist时就会自动跳转到指定的时间位置播放。

> 好想法，应该比较容易实现，后面有时间我尝试尝试（虽然我目前没有这方面的需求）

我已经实现了。

效果如下

![r80](https://github.com/user-attachments/assets/7b97d28c-aea3-4380-a4a3-d4b5c238fb57)


代码如下（把以下代码放到alist管理页面，设置-》全局-》自定义内容里即可）

```html
<script>
(function() {
    // 监听哪些视频格式
    const videos = ['.mp4','.avi', '.webm', '.ogg'];
    // 监听哪些音频格式
    const audios = ['.mp3', '.wav', '.m4a'];
    
    // 监听视频格式
    observeElementExist('a[href^="iina://"]', a => {
        if(!videos.some(extension => location.pathname.endsWith(extension))){
            return;
        }
        const shareBtn = document.createElement('button');
        shareBtn.textContent = "复制";
        shareBtn.style.padding = '0px 15px';
        shareBtn.onclick = () => {
            const title = document.querySelector('nav ol li:last-child').textContent;
            const video = document.querySelector('video');
            const time = video.currentTime;
            const text = `[${title} [${convertSecondsToMinutesAndSeconds(time)}]](${genUrlParameter(location.href, 'time', time)})`;
            navigator.clipboard.writeText(text);
            shareBtn.textContent = "已复制";
            setTimeout(() => { shareBtn.textContent = "复制"; }, 1500);
        };
        // 将shareBtn插入到目标a元素之前
        a.parentElement.insertBefore(shareBtn, a);

        //获取URL参数并调整到对应的时间
        const time = parseFloat(getUrlParameter(location.href, 'time'));
        if(time){
            const lastPlayTips = document.querySelector('.art-layer.art-layer-auto-playback');
            if(lastPlayTips) lastPlayTips.style.display = 'none';
            const video = document.querySelector('video');
            video.currentTime = time;
        }
    });
    
    //监听音频格式化(不支持获取当前时间，因为无法获取aplayer播放器实例)
    observeElementExist('.aplayer-music', el => {
        if(el.dataset.loaded === 'true') return;
        el.dataset.loaded = true;
        if(!audios.some(extension => location.pathname.endsWith(extension))){
            return;
        }
       el.style.overflow = 'visible';
        const shareBtn = document.createElement('button');
        shareBtn.textContent = "复制";
        shareBtn.style.padding = '0px 5px';
        shareBtn.style.float = 'right';
        shareBtn.onclick = () => {
            const title = el.querySelector('.aplayer-title').textContent;
            const text = `[${title}](${location.href})`;
            navigator.clipboard.writeText(text);
            shareBtn.textContent = "已复制";
            setTimeout(() => { shareBtn.textContent = "复制"; }, 1500);
        };
        el.appendChild(shareBtn);
    });

    function getUrlParameter(url, param) {
        const urlParams = new URLSearchParams(new URL(url).search);
        return urlParams.get(param);
    }
    function genUrlParameter(url, param, value) {
        const urlParams = new URLSearchParams(new URL(url).search);
        urlParams.set(param, value);
        const newUrl = url.split('?')[0] + '?' + urlParams.toString();
        return newUrl;
    }
    function convertSecondsToMinutesAndSeconds(seconds) {
        let minutes = Math.floor(seconds / 60);
        const secondsRemaining = Math.floor(seconds % 60);
    
        // 格式化分秒数
        const formattedSeconds = secondsRemaining.toString().padStart(2, '0');
        minutes = minutes.toString().padStart(2, '0');
        return `${minutes}:${formattedSeconds}`;
    }
    function observeElementExist(selector, callback) {
        const handleMutations = (mutationsList, observer) => {
            for (let mutation of mutationsList) {
                if (mutation.type === 'childList') {
                    mutation.addedNodes.forEach(node => {
                        if (node.matches && node.matches(selector)) {
                            callback(node);
                        } else if (node && node.querySelector && node.querySelector(selector)) {
                            callback(node.querySelector(selector));
                        }
                    });
                }
            }
        };
    
        // 创建一个MutationObserver实例
        const config = { attributes: false, childList: true, subtree: true };
        const observer = new MutationObserver(handleMutations);
    
        // 选择需要监听的父节点
        const targetNode = document.body; // 或者选择其他合适的父节点
    
        // 开始监听目标节点的变化
        observer.observe(targetNode, config);
    }
})();
</script>
```

**Comment by loonghfut** [comment]
> 我已经实现了。
感谢大佬🙏🏼

**Comment by loonghfut** [comment]
> 已知问题： 音频不支持自动定位到指定时间，因为外部无法获取到aplayer播放器的实例，无法控制，如果大佬知道的话，麻烦告知下，谢谢！

这我目前也无法解决，
其实我只是个编程小白( ᵒ̴̶̷̤໐ᵒ̴̶̷̤ )
（编程语言也只是课外学的，[半斤八两 (*꒦ິ⌓꒦ີ)]）

**Comment by loonghfut** [comment]
> 这个可以有。

好，最近有点忙，我尽快弄

**Comment by loonghfut** [comment]
> > 这个可以有。
> 
> 好，最近有点忙，我尽快弄

插件已更新，万分感谢对此插件相关的贡献

**Comment by wish5115** [comment]
> > > 这个可以有。
> > 
> > 
> > 好，最近有点忙，我尽快弄
> 
> 插件已更新，万分感谢您对此插件相关的贡献

👍 

我测试了下，默认情况下，插件和思源默认的ctrl+点击用浏览器打开冲突，所以ctrl并未生效，不过也不会弹出左侧面板了，这个功能相当于开启关闭左侧面板的选项了，也达到了解决与其他插件冲突的目的。

**Comment by loonghfut** [comment]
> 所以ctrl并未生效，不过也不会弹出左侧面板了

嗯？我这边没有问题，难道其他两个插件也监听了这个事件？你把那两个插件关了再试试，如果是这样我再考虑加一个关闭触发的选择。

**Comment by loonghfut** [comment]
https://github.com/user-attachments/assets/77b9dbf5-245d-4e1f-8848-e84df03cd976

**Comment by wish5115** [comment]
> 2024-10-23.133026.mp4

你的视频中好像安装了网页浏览器后的效果。

我这边的情况是，在alist插件开启ctrl+左键触发时，无论是否安装了网页插件，ctrl+单击都会跳转到浏览器打开。

建议别用CTRL+左键，这与思源自带的热键冲突而失效，建议换个按键或者允许用户自定义按键。

**Comment by loonghfut** [comment]
> > 2024-10-23.133026.mp4
> 
> 你的视频中好像安装了网页浏览器后的效果。
> 
> 我这边的情况是，在alist插件开启ctrl+左键触发时，无论是否安装了网页插件，ctrl+单击都会跳转到浏览器打开。
> 
> 建议别用CTRL+左键，这与思源自带的热键冲突而失效，建议换个按键或者允许用户自定义按键。

好的

**Comment by loonghfut** [comment]
> 建议换个按键或者允许用户自定义按键。

似乎可以和左键联系的键很少，如果是`z+左键`会导致在笔记里输入z，似乎只有ctrl，shift，alt，capslock（勉强可以）
 
要和鼠标左键配合的键必须满足，这个键单独按下不会产生什么效果（或者产生的效果比较小eg：shift）
测试了一个小时左右，发现F1，F9等F功能键有些没有绑定其他效果，如果要实现用户自定义的话，最好在F1到F12中选。
我还有个想法，将触发方式改为alt+左键，既然有其他插件实现原来的alt+左键的效果，那就把之前的alt+左键改为侧边栏触发（打算做一个配置选项）

**Comment by wish5115** [comment]
> > 建议换个按键或者允许用户自定义按键。
> 
> 似乎可以和左键联系的键很少，如果是`z+左键`会导致在笔记里输入z，似乎只有ctrl，shift，alt，capslock（勉强可以）
> 
> 要和鼠标左键配合的键必须满足，这个键单独按下不会产生什么效果（或者产生的效果比较小eg：shift） 测试了一个小时左右，发现F1，F9等F功能键有些没有绑定其他效果，如果要实现用户自定义的话，最好在F1到F12中选。 我还有个想法，将触发方式改为alt+左键，既然有其他插件实现原来的alt+左键的效果，那就把之前的alt+左键改为侧边栏触发（打算做一个配置选项）

大佬辛苦了！

alt+单击是链接在右侧分屏打开，思源已经有了。

本来可以使用组合键的 比如 ctrl+alt+单击，但思源的快捷键有问题，只要有ctrl键，所有的组合都会触发，我等会给官方提供bug。

目前看来好像，确实很难选组合键，希望后续官方快捷键能改进下。

**Comment by loonghfut** [comment]
> alt+单击是链接在右侧分屏打开，思源已经有了。

我新开了一个笔记空间试了下alt+单击是思源内部链接在右侧分屏打开，我插件监听alt＋单击后会判断点击的是不是alist链接，是才触发效果。

不知道多个代码都监听同一个事件是否会产生bug

**Comment by wish5115** [comment]
另外，建议发布服务下，屏蔽一些功能，比如备份，上传等。

参考 issue https://github.com/siyuan-note/siyuan/issues/12928#issuecomment-2439896607

**Comment by loonghfut** [comment]
> 另外，建议发布服务下，屏蔽一些功能，比如备份，上传等。

了解（我还从来没有考虑过这个问题），但是插件如何知晓笔记是否处于发布服务下（目前我还未了解过）
目前有相关api可以判断吗

**Comment by wish5115** [comment]
> > 另外，建议发布服务下，屏蔽一些功能，比如备份，上传等。
> 
> 了解（我还从来没有考虑过这个问题），但是插件如何知晓笔记是否处于发布服务下（目前我还未了解过） 目前有相关api可以判断吗

通过全局变量siyuan.config.readonly可判断

**Comment by loonghfut** [comment]
> 建议发布服务下，屏蔽一些功能

尽管屏蔽了功能，但如果使用了本插件并使用了发布服务，就会使自己的alist网址暴露出来，所以如果使用了发布服务还得加强alist服务的保护（比如设置一个更复杂的密码，二次验证）

我刚刚在调试的时候，发现尽管处于发布服务状态下，插件还是可以读取到插件的配置信息（插件开发用的是社区的模板）

**Comment by loonghfut** [comment]
> 发现尽管处于发布服务状态下，插件还是可以读取到插件的配置信息（

你可以在更新0.0.8之前，测试一下
（进入发布状态下，查看网站日志）

**Comment by wish5115** [comment]
👍 确实，0.0.8好了，能有效屏蔽隐私数据被泄漏

**Comment by loonghfut** [comment]
> 这个可能是思源的问题，思源嵌入网页都有可能出现这种情况 

目前最新版本已解决（不是思源的问题，我一直误解思源了，思源yyds！）
