### ISSUE TITLE
1.设置自动备份后，系统重载，然后就一直卡在启动页面

### ISSUE THREAD

**Issue by vicnoah** [loonghfut/siyuan-alist#3]
1.插件在疯狂重新备份，没法做任何操作了。
![image](https://github.com/user-attachments/assets/e414d897-337f-48d1-a4d5-5c03d8ca4d6a)
![recording](https://github.com/user-attachments/assets/46c2b910-d563-4f87-b6b5-f5a8a9ae446a)

**Comment by loonghfut** [comment]
> 感谢反馈，这应该是插件错误处理做的不完善，后面版本改进

你设置定时备份时，填的是什么

紧急处理措施：在资源文件管理器里先把本插件文件夹删了

**Comment by vicnoah** [comment]
> > 感谢反馈，这应该是插件错误处理做的不完善，后面版本改进
> 
> 你设置定时备份时，填的是什么
> 
> 紧急处理措施：在资源文件管理器里先把本插件文件夹删了

填的是5:00,然后突然闪退了。估计没有成功保存

**Comment by loonghfut** [comment]
> > > 感谢反馈，这应该是插件错误处理做的不完善，后面版本改进
> > 
> > 你设置定时备份时，填的是什么
> > 
> > 紧急处理措施：在资源文件管理器里先把本插件文件夹删了
> 
> 填的是5:00,然后突然闪退了。估计没有成功保存

你格式填错了应该填05/00

**Comment by vicnoah** [comment]
> > 感谢反馈，这应该是插件错误处理做的不完善，后面版本改进
> 
> 你设置定时备份时，填的是什么
> 
> 紧急处理措施：在资源文件管理器里先把本插件文件夹删了

资源文件管理器是指的什么呢？我没找到

**Comment by vicnoah** [comment]
> ![IMG_20241108_162241.jpg](https://private-user-images.githubusercontent.com/165535596/384284048-e5c6d0a2-db19-4603-b869-c97e8e45945a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTQ1MzgsIm5iZiI6MTczMTA1NDIzOCwicGF0aCI6Ii8xNjU1MzU1OTYvMzg0Mjg0MDQ4LWU1YzZkMGEyLWRiMTktNDYwMy1iODY5LWM5N2U4ZTQ1OTQ1YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwODIzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmQ0YjI5ZDAwZDg0MTg2ODJmMDQ1YzgxNGI1ZGRmNTViNDMwNWU2ZDY0OTBmNjBjNDE2ZjQxYjQxZWFkODg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KrBVqLv1DrQ1g62lPuDZkZrszHt000kIuC5PYdPL4DM)
> 
> 你应该没注意看功能的介绍，当然这也是我的问题，提示不够醒目

好的，我看看

**Comment by loonghfut** [comment]
如果重新下载插件还会出问题，就把这个文件删了，再重新安装
data\storage\petal\siyuan-alist\menu-config.json

**Comment by vicnoah** [comment]
> 如果重新下载插件还会出问题，就把这个文件删了，再重新安装 data\storage\petal\siyuan-alist\menu-config.json

![image](https://github.com/user-attachments/assets/ee40d1b9-4799-4e08-9f1a-eb30ce5f2cbe)
看到了，可以直接在这改吗？

**Comment by loonghfut** [comment]
> 看到了，可以直接在这改吗？

可以

**Comment by vicnoah** [comment]
> > 看到了，可以直接在这改吗？
> 
> 可以
好了，谢谢
