### ISSUE TITLE
插件使用https://xxx.com无法验收网络，无法使用。

### ISSUE THREAD

**Issue by taliszhou** [loonghfut/siyuan-alist#4]
我尝试部署使用这个插件，Alist 我也部署好在内网，插件配置如果是 http://192.168.1.123 这样 http 的形式，点击那个验证以及后续上传使用都能够正常。

但我目标是能够在外网进行使用 alist，所以我是部署了 https 代理的，证书也确定是可信任的（浏览器不会报一个异常再让你继续访问）。 可是在插件配置页面输入了确定正确的域名及账号信息，可一直提示网络错误。

我尝试不用https，直接使用http协议，也是能够正常从公网通过域名访问使用，但就太不安全了。

请指导，谢谢

**Comment by loonghfut** [comment]
看了你描述的问题，我也不清楚怎么解决，我就是alist部署在外网的且使用正常，你可以先用浏览器试试你的alist能在外网访问吗

你也可以提供控制台的报错日志（win端在开发者工具里，如果是浏览器使用思源，按F12可以看到控制台日志）

注意：提供日志的时候，不要泄露个人信息

**Comment by loonghfut** [comment]
看了你描述的问题，我也不清楚怎么解决，我就是alist部署在外网的且使用正常，你可以先用浏览器试试你的alist能在外网访问吗

你也可以提供控制台的报错日志（win端在开发者工具里，如果是浏览器使用思源，按F12可以看到控制台日志）

注意：提供日志的时候，不要泄露个人信息


你也可以点下侧边栏的alist按钮，看看能不能加载出页面

**Comment by loonghfut** [comment]
> 我尝试不用https，直接使用http协议，也是能够正常从公网通过域名访问使用，但就太不安全了。

你是在哪个平台使用思源笔记的

**Comment by loonghfut** [comment]
日志上显示这个问题出现在证书上，你用浏览器是通过https访问alist的吗？

还有一种排查问题的办法，你试试下载插件市场里的[browserTab](https://github.com/leolee9086/browserTab)然后再输入你的alist网址看看能不能正常使用

**Comment by loonghfut** [comment]
mac端，我没有设备无法测试是否是插件的问题，win端插件是没有问题的

**Comment by loonghfut** [comment]
还有一种测试方法：
![1731494137644](https://github.com/user-attachments/assets/175c74a7-7bfd-44c9-b738-dec2eae92824)
在配置里输入这个，再点击右侧的alist icon看看能不能显示百度页面
