### ISSUE TITLE
可以增加一个功能，一键把assets中的文件上传到alist中并用新的链接代替吗？

### ISSUE THREAD

**Issue by BoysFight** [loonghfut/siyuan-alist#5]
背景
当前assets目录下有些比较大的文件，想要迁移到alist中需要先上传，然后再查找替换原来的链接，比较麻烦。

**Comment by loonghfut** [comment]
感谢反馈
是有这个计划的 [readme](https://github.com/loonghfut/siyuan-alist#:~:text=TODO%3A%E6%94%AF%E6%8C%81%E5%B0%86%E6%80%9D%E6%BA%90%E7%AC%94%E8%AE%B0%E9%87%8C%E7%9A%84%E9%99%84%E4%BB%B6%E4%B8%8A%E4%BC%A0%E5%88%B0alist%E5%B9%B6%E6%9B%BF%E6%8D%A2%E9%93%BE%E6%8E%A5) 
但实现方式可能不会是一键解决（这种方式文件多了容易出bug），而是单个选择上传。

预计下个版本实现

**Comment by loonghfut** [comment]
v0.0.11
