### ISSUE TITLE
无法缩小插件页面，占用笔记软件过大页面面积

### ISSUE THREAD

**Issue by SkysCrystal** [loonghfut/siyuan-alist#7]
操作：打开插件页面，拖动图中红框部分调整页面大小。
问题：右侧的插件页面，变小到图中的尺寸后就无法再变小了，占用了过多的页面，左侧正文只有很小的空间。
![siyuan_bug](https://github.com/user-attachments/assets/4cf9c0ac-1f1f-4c51-b5bb-c4617d5f3621)

当我右键调整插件：移动到右侧下方后，又可以变成一个很小的部分。但是一旦拖动插件页面放大后，又遇到无法缩小的问题。
![siyuan_bug2](https://github.com/user-attachments/assets/31571a5b-e149-489e-8aa4-09ba7c877bb3)

**Comment by SkysCrystal** [comment]
提及： https://github.com/loonghfut/siyuan-alist/issues/2?utm_source=ld246.com#issuecomment-2424494316

> 目前解决办法： 拖动的时候将鼠标移动到思源笔记的下方或上方（文档栏里）

**Comment by loonghfut** [comment]
> 提及： #2
> 
> > 目前解决办法： 拖动的时候将鼠标移动到思源笔记的下方或上方（文档栏里）

目前最新版本已解决（不是思源的问题，我一直误解思源了）
