### ISSUE TITLE
希望默认备份名新增时间戳变量

### ISSUE THREAD

**Issue by AWicls** [loonghfut/siyuan-alist#8]
- 请求添加相关时间戳变量以满足每日默认增量备份, 而不是覆盖旧版本文件备份

**Comment by loonghfut** [comment]
其实可以每次备份的时候改下文件名，额，，，不过不怎么方便，好的，下个版本改进

感谢反馈，你如果不提我可能永远不会改，因为我没怎么用备份的功能。
