### ISSUE TITLE
时间戳不会更新

### ISSUE THREAD

**Issue by AWicls** [loonghfut/siyuan-alist#9]
- 点击全量备份后第一次会获取当前时间, 后面全部沿用了第一次获取的时间
- 希望可以自定义时间戳位置

**Comment by loonghfut** [comment]
若没有达到您的预期，请再把这个issue打开

**Comment by AWicls** [comment]
> 首先感谢`loonghfut`开发者积极维护项目并解决bug

### 相关问题截图
![image](https://github.com/user-attachments/assets/cb666951-59be-4a79-8acc-9fc56bcb9b20)

### 其他问题
1. 首先默认备份名为`siyuan-backup-${timeNow}.zip`, 出现了如图情况, 首部还是有时间戳, 时间戳可以做到自动更新
    - 期望: 不加时间戳变量就没有时间戳
2. 默认备份名为`siyuan-backup.zip`时, 前面的时间戳并不会更新
    - 如果实现问题一期望此问题就应该没了

**Comment by loonghfut** [comment]
> 首部还是有时间戳, 

当时改得有点匆忙，我调试的代码没删干净(ㄒoㄒ)，因为思源目录里有软连接无法导出data，所以当时没有测试，我平时又用的docker端，很少用到这个功能。

> 首先感谢loonghfut开发者积极维护项目并解决bug

还好有你反馈，让我发现问题。

对了，如需要，后续版本可以添加将alist备份的思源data.zip文件，导入思源中（可以在新设备上方便地导入数据）【有点同步那意思，但强烈不建议同步使用，用作同步体验非常糟糕】
这个功能我没有需求，所以当时没写，不知您是否需要
